name: newbie_flutter
description: A new Flutter application for newbie.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  appcenter:
    git:
      url: git://github.com/nhancv/flutter_plugin_appcenter.git
      path: src/appcenter
  appcenter_crashes:
    git:
      url: git://github.com/nhancv/flutter_plugin_appcenter.git
      path: src/appcenter_crashes
  appcenter_analytics:
    git:
      url: git://github.com/nhancv/flutter_plugin_appcenter.git
      path: src/appcenter_analytics

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
